// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZonePostings.Models;

namespace ZonePostings.Migrations.Player
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20190701173628_CommitThird")]
    partial class CommitThird
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("ZonePostings.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Equipment");

                    b.Property<int>("Health");

                    b.Property<string>("Name");

                    b.Property<int>("Savings");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ZonePostings.Models.Posting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Available");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Payout");

                    b.Property<int?>("PlayerId");

                    b.Property<int>("Risk");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Posting");
                });

            modelBuilder.Entity("ZonePostings.Models.Posting", b =>
                {
                    b.HasOne("ZonePostings.Models.Player")
                        .WithMany("AssignedPostings")
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
